declare module "@medusajs/framework/types" {
  export type MedusaContainer = any
}

declare module "@medusajs/core-flows" {
  export const cancelOrderWorkflow: any
  export const capturePaymentWorkflow: any
  export const createLocationFulfillmentSetWorkflow: any
  export const createServiceZonesWorkflow: any
  export const createShippingOptionsWorkflow: any
  export const createShippingProfilesWorkflow: any
  export const createStockLocationsWorkflow: any
  export const linkSalesChannelsToStockLocationWorkflow: any
  export const updateShippingOptionsWorkflow: any
  export const createOrderFulfillmentWorkflow: any
  export const createShipmentWorkflow: any
  export const createPaymentCaptureWorkflow: any
  export const createPaymentSessionsWorkflow: any
  export const refreshPaymentSessionsWorkflow: any
  export const authorizePaymentSessionWorkflow: any
  export const refundPaymentWorkflow: any
  export const refundPaymentsWorkflow: any
  export const processPaymentWorkflow: any
  export const deletePaymentSessionsWorkflow: any
  export const createFulfillmentWorkflow: any
  export const cancelFulfillmentWorkflow: any
  export const deliveryOrderWorkflow: any
  export const cancelOrderFulfillmentWorkflow: any
  export const receiveOrderReturnWorkflow: any
  export const cancelReturnWorkflow: any
  export const requestOrderReturnWorkflow: any
  export const createOrderSwapWorkflow: any
  export const cancelOrderSwapWorkflow: any
  export const createSwapShipmentWorkflow: any
  export const createSwapFulfillmentWorkflow: any
  export const receiveSwapWorkflow: any
  export const processSwapPaymentWorkflow: any
  export const updateOrderWorkflow: any
  export const placeOrderWorkflow: any
  export const completeCartWorkflow: any
  export const createCartWorkflow: any
  export const updateCartWorkflow: any
  export const addToCartWorkflow: any
  export const updateLineItemInCartWorkflow: any
  export const removeLineItemFromCartWorkflow: any
  export const deleteLineItemWorkflow: any
  export const transferCustomerCartWorkflow: any
  export const createPaymentSessionWorkflow: any
  export const updatePaymentSessionsWorkflow: any
  export const deletePaymentSessionWorkflow: any
  export const createProductWorkflow: any
  export const updateProductWorkflow: any
  export const deleteProductWorkflow: any
  export const createVariantWorkflow: any
  export const updateVariantWorkflow: any
  export const deleteVariantWorkflow: any
  export const createCategoryWorkflow: any
  export const updateCategoryWorkflow: any
  export const deleteCategoryWorkflow: any
  export const createCustomerWorkflow: any
  export const updateCustomerWorkflow: any
  export const deleteCustomerWorkflow: any
  export const createRegionWorkflow: any
  export const updateRegionWorkflow: any
  export const deleteRegionWorkflow: any
  export const createSalesChannelWorkflow: any
  export const updateSalesChannelWorkflow: any
  export const deleteSalesChannelWorkflow: any
  export const createStockLocationWorkflow: any
  export const updateStockLocationWorkflow: any
  export const deleteStockLocationWorkflow: any
  export const createInventoryLevelWorkflow: any
  export const updateInventoryLevelWorkflow: any
  export const deleteInventoryLevelWorkflow: any
  export const createPriceListWorkflow: any
  export const updatePriceListWorkflow: any
  export const deletePriceListWorkflow: any
  export const createPromotionWorkflow: any
  export const updatePromotionWorkflow: any
  export const deletePromotionWorkflow: any
  export const createApiKeyWorkflow: any
  export const updateApiKeyWorkflow: any
  export const deleteApiKeyWorkflow: any
  export const createStoreWorkflow: any
  export const updateStoreWorkflow: any
  export const deleteUserWorkflow: any
  export const updateUserWorkflow: any
  export const createPublishableApiKeyWorkflow: any
  export const createAdminAccountWorkflow: any
  export const createSellerAccountWorkflow: any
  export const registerCustomerWorkflow: any
  export const authenticateCustomerWorkflow: any
  export const generateResetPasswordTokenWorkflow: any
  export const resetPasswordWorkflow: any
  export const updatePasswordWorkflow: any
  export const createNotificationWorkflow: any
  export const sendNotificationWorkflow: any
  export const createFileWorkflow: any
  export const deleteFileWorkflow: any
  export const createUploadWorkflow: any
  export const createTaxRateWorkflow: any
  export const updateTaxRateWorkflow: any
  export const deleteTaxRateWorkflow: any
  export const createTaxRegionWorkflow: any
  export const updateTaxRegionWorkflow: any
  export const deleteTaxRegionWorkflow: any
  export const createFulfillmentSetWorkflow: any
  export const updateFulfillmentSetWorkflow: any
  export const deleteFulfillmentSetWorkflow: any
  export const createServiceZoneWorkflow: any
  export const updateServiceZoneWorkflow: any
  export const deleteServiceZoneWorkflow: any
  export const createGeoZoneWorkflow: any
  export const updateGeoZoneWorkflow: any
  export const deleteGeoZoneWorkflow: any
  export const createPaymentProviderWorkflow: any
  export const updatePaymentProviderWorkflow: any
  export const deletePaymentProviderWorkflow: any
  export const createFulfillmentProviderWorkflow: any
  export const updateFulfillmentProviderWorkflow: any
  export const deleteFulfillmentProviderWorkflow: any
  export const createNotificationProviderWorkflow: any
  export const updateNotificationProviderWorkflow: any
  export const deleteNotificationProviderWorkflow: any
  export const createTaxProviderWorkflow: any
  export const updateTaxProviderWorkflow: any
  export const deleteTaxProviderWorkflow: any
  export const createCurrencyWorkflow: any
  export const updateCurrencyWorkflow: any
  export const deleteCurrencyWorkflow: any
  export const createDraftOrderWorkflow: any
  export const updateDraftOrderWorkflow: any
  export const deleteDraftOrderWorkflow: any
  export const createReturnWorkflow: any
  export const updateReturnWorkflow: any
  export const deleteReturnWorkflow: any
  export const createClaimWorkflow: any
  export const updateClaimWorkflow: any
  export const deleteClaimWorkflow: any
  export const createExchangeWorkflow: any
  export const updateExchangeWorkflow: any
  export const deleteExchangeWorkflow: any
  export const createPaymentCollectionWorkflow: any
  export const updatePaymentCollectionWorkflow: any
  export const deletePaymentCollectionWorkflow: any
  export const createPaymentWorkflow: any
  export const updatePaymentWorkflow: any
  export const deletePaymentWorkflow: any
  export const createRefundWorkflow: any
  export const updateRefundWorkflow: any
  export const deleteRefundWorkflow: any
  export const createTransactionWorkflow: any
  export const updateTransactionWorkflow: any
  export const deleteTransactionWorkflow: any
  export const createReservationWorkflow: any
  export const updateReservationWorkflow: any
  export const deleteReservationWorkflow: any
  export const createLocationLevelWorkflow: any
  export const updateLocationLevelWorkflow: any
  export const deleteLocationLevelWorkflow: any
  export const createProductVariantInventoryWorkflow: any
  export const updateProductVariantInventoryWorkflow: any
  export const deleteProductVariantInventoryWorkflow: any
  export const createProductOptionWorkflow: any
  export const updateProductOptionWorkflow: any
  export const deleteProductOptionWorkflow: any
  export const createProductOptionValueWorkflow: any
  export const updateProductOptionValueWorkflow: any
  export const deleteProductOptionValueWorkflow: any
  export const createProductTagWorkflow: any
  export const updateProductTagWorkflow: any
  export const deleteProductTagWorkflow: any
  export const createProductTypeWorkflow: any
  export const updateProductTypeWorkflow: any
  export const deleteProductTypeWorkflow: any
  export const createProductImageWorkflow: any
  export const updateProductImageWorkflow: any
  export const deleteProductImageWorkflow: any
  export const createProductVariantOptionWorkflow: any
  export const updateProductVariantOptionWorkflow: any
  export const deleteProductVariantOptionWorkflow: any
  export const createProductVariantPriceWorkflow: any
  export const updateProductVariantPriceWorkflow: any
  export const deleteProductVariantPriceWorkflow: any
  export const createProductVariantInventoryItemWorkflow: any
  export const updateProductVariantInventoryItemWorkflow: any
  export const deleteProductVariantInventoryItemWorkflow: any
  export const createProductVariantPriceSetWorkflow: any
  export const updateProductVariantPriceSetWorkflow: any
  export const deleteProductVariantPriceSetWorkflow: any
  export const createProductVariantShippingProfileWorkflow: any
  export const updateProductVariantShippingProfileWorkflow: any
  export const deleteProductVariantShippingProfileWorkflow: any
  export const createProductVariantTaxRateWorkflow: any
  export const updateProductVariantTaxRateWorkflow: any
  export const deleteProductVariantTaxRateWorkflow: any
}
