import { model } from "@medusajs/framework/utils"

const BuyerRefundRequest = model.define("buyer_refund_request", {
  id: model.id({ prefix: "brr" }).primaryKey(),
  order_id: model.text(),
  display_id: model.number().nullable(),
  customer_id: model.text(),
  store_id: model.text(),
  currency_code: model.text(),
  requested_amount: model.bigNumber(),
  eligible_amount: model.bigNumber().nullable(),
  approved_amount: model.bigNumber().nullable(),
  requested_items: model.json().nullable(),
  reason: model.text(),
  note: model.text().nullable(),
  status: model
    .enum([
      "pending",
      "requested",
      "auto_review",
      "manual_review",
      "awaiting_information",
      "approved",
      "rejected",
      "processing",
      "refund_processing",
      "partially_refunded",
      "refunded",
      "refund_pending",
      "refund_failed",
      "processed",
      "failed",
      "cancelled",
    ])
    .default("pending"),
  payment_provider_id: model.text().nullable(),
  external_payment_id: model.text().nullable(),
  external_refund_id: model.text().nullable(),
  external_transaction_id: model.text().nullable(),
  provider_status: model.text().nullable(),
  provider_payload: model.json().nullable(),
  reviewed_at: model.dateTime().nullable(),
  processed_at: model.dateTime().nullable(),
  failed_at: model.dateTime().nullable(),
  failure_reason: model.text().nullable(),
  policy_result: model.text().nullable(),
  decision_type: model.text().nullable(),
  decision_reason: model.text().nullable(),
  reviewed_by: model.text().nullable(),
  production_status_snapshot: model.text().nullable(),
  latest_production_status: model.text().nullable(),
  idempotency_key: model.text().nullable(),
  attempt_count: model.number().default(0),
  last_provider_error_code: model.text().nullable(),
  metadata: model.json().nullable(),
})

export default BuyerRefundRequest
