export const ErrorCodes = {
  STORE_NOT_FOUND: "STORE_NOT_FOUND",
  STORE_ACCESS_DENIED: "STORE_ACCESS_DENIED",
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_NOT_PUBLISHED: "PRODUCT_NOT_PUBLISHED",
  PRODUCT_STORE_MISMATCH: "PRODUCT_STORE_MISMATCH",
  CART_STORE_MISMATCH: "CART_STORE_MISMATCH",
  /** 当前请求的 store 与购物车 metadata.store_id 不一致 */
  CART_STORE_ACCESS_DENIED: "CART_STORE_ACCESS_DENIED",
  ORDER_STORE_MISMATCH: "ORDER_STORE_MISMATCH",
  /** 当前店与订单 metadata.store_id 不一致 */
  ORDER_STORE_ACCESS_DENIED: "ORDER_STORE_ACCESS_DENIED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  STRIPE_NOT_CONFIGURED: "STRIPE_NOT_CONFIGURED",
  STRIPE_CONNECT_ONBOARDING_FAILED: "STRIPE_CONNECT_ONBOARDING_FAILED",
  STRIPE_WEBHOOK_INVALID: "STRIPE_WEBHOOK_INVALID",
  REVIEW_NOT_ALLOWED: "REVIEW_NOT_ALLOWED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  DESIGNER_NOT_SUPPORTED: "DESIGNER_NOT_SUPPORTED",
  SUPPLIER_UNAVAILABLE: "SUPPLIER_UNAVAILABLE",
  SUPPLIER_AUTH_FAILED: "SUPPLIER_AUTH_FAILED",
  S2BDIY_CREDENTIALS_REQUIRED: "S2BDIY_CREDENTIALS_REQUIRED",
  S2BDIY_CREDENTIALS_INVALID: "S2BDIY_CREDENTIALS_INVALID",
  S2B_PRODUCT_ID_REQUIRED: "S2B_PRODUCT_ID_REQUIRED",
  S2BDIY_MOCK_MODE: "S2BDIY_MOCK_MODE",
  S2B_MOCKUP_NOT_FOUND: "S2B_MOCKUP_NOT_FOUND",
  S2B_SYNC_FAILED: "S2B_SYNC_FAILED",
  MISSING_FIELDS: "MISSING_FIELDS",
  DESIGN_COMPLETE_FAILED: "DESIGN_COMPLETE_FAILED",
  NOT_FOUND: "NOT_FOUND",
  EXTERNAL_SERVICE_ERROR: "EXTERNAL_SERVICE_ERROR",
  // Custom editor proxy errors
  S2BDIY_NOT_CONFIGURED: "S2BDIY_NOT_CONFIGURED",
  INVALID_ID: "INVALID_ID",
  PRODUCT_DETAIL_FAILED: "PRODUCT_DETAIL_FAILED",
  PRODUCT_DETAIL_ERROR: "PRODUCT_DETAIL_ERROR",
  QUICK_CREATE_FAILED: "QUICK_CREATE_FAILED",
  QUICK_CREATE_ERROR: "QUICK_CREATE_ERROR"
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export const errorResponse = (code: ErrorCode, message: string, status = 400) => ({
  status,
  body: {
    error: {
      code,
      message
    }
  }
})

